name: Release

on:
  push:
    tags:
      - 'v*' # 当推送v开头的tag时触发

jobs:
  release:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
      
    - name: Build project
      run: npm run build
      
    - name: Package application
      run: npm run package

    - name: Determine artifact extension
      id: artifact
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          echo "extension=exe" >> $GITHUB_ENV
        elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          echo "extension=zip" >> $GITHUB_ENV
        else
          echo "extension=AppImage" >> $GITHUB_ENV
        fi
      
    - name: Create Release
      if: matrix.os == 'ubuntu-latest' # 只在ubuntu runner上创建release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        generate_release_notes: true
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/*.${{ env.extension }}
        asset_name: APTXCODE-${{ github.ref }}-${{ runner.arch }}-${{ matrix.os }}.${{ env.extension }}
        asset_content_type: application/octet-stream
